---
version: '3.9'

services:
  wordpress:
    image: wordpress:latest
    ports:
      - 80:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: codica-rds.ckta7d6pblur.eu-central-1.rds.amazonaws.com:3306
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: CODICAexample
      WORDPRESS_DB_NAME: wordpress
volumes:
    wp_data: